version: '3.8'

services:
  bananzza-postgres:
    image: postgres:14
    container_name: bananzza
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data
    networks:
      - goapp-network


  bananzza-gomarket:
    build: .
    restart: on-failure
    depends_on:
      bananzza-postgres:
        condition: service_healthy
    env_file:
      - env/bananzza.env


volumes:
  pgdata1:

networks:
  goapp-network:
    driver: bridge
