global:
  scrape_interval: 15s # Как часто опрашивать цели по умолчанию
  evaluation_interval: 15s # Как часто пересчитывать правила

scrape_configs:
  # Задача для сбора метрик с самого Prometheus (полезно для отладки)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Задача для сбора метрик с вашего Product Service API
  - job_name: 'product-service-api'
    # Используйте DNS имя сервиса из docker-compose.yml и порт ВНУТРИ контейнера
    static_configs:
      - targets: ['product-api:8080'] # 'product-api' - имя сервиса, 8080 - порт приложения внутри контейнера
    metrics_path: /metrics

  # Worker service metrics
  - job_name: 'product-service-worker'
    static_configs:
      - targets: ['product-worker:8080'] # Worker service metrics endpoint
    metrics_path: /metrics